version: "3"
services:
  ros2:
    build:
      context: ./docker
      args:
        ROS_DISTRO: foxy
    volumes:
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    tty: true